TLF-285-add missing validations
UKHomeOffice/ecs pull request #22
Opened 2024-08-12 16:35 UTC by RobertMcCann

Relates [TLF-285](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-285)

What
Add missing validation messages and logic to fields

2024-08-15 08:39 UTC, vinodhasamiyappanHO approved these changes
Looks good to me.

2024-08-15 10:18 UTC, dk4g requested changes

2024-08-15 10:18 UTC, dk4g commented on apps/ecs/behaviours/check-validation.js
> +      if (yearOfEntry && yearOfEntry >= '1988') {
`yearOfEntry >= '1988'` is a string comparison, which can lead to incorrect results. Both needs to be converted to number first.

`Number(yearOfEntry) >= 1988`

or convert  `Number(yearOfEntry)` at line 32 and trigger validation error straight after if it's `NaN`

2024-08-15 10:18 UTC, dk4g commented on apps/ecs/behaviours/check-validation.js
> +         && yearOfEntry < moment(workerDob).format('YYYY') && workerDob) {
same applies here for comparing years, need to be converted to Number first

2024-08-15 10:18 UTC, dk4g commented on apps/ecs/fields/index.js
> +    validate: ['ukPhoneNumber', 'required'],
change order, so `required` check will be triggered first

2024-08-15 10:30 UTC, dk4g commented on apps/ecs/behaviours/check-validation.js
> +      if (yearOfEntry && yearOfEntry >= '1988') {
Given that `before-1988-worker-year-of-entry-to-uk` is a text input, it would be correct to use `Number.parseInt()` in this case

2024-08-16 11:00 UTC, dk4g commented on apps/ecs/behaviours/check-validation.js
>        if (yearOfEntry && yearOfEntry <= oneHundredTwentyYearsAgo) {
I would suggest to rename the variable to be more generic, for example `minYearOfEntry`

2024-08-16 14:52 UTC, merged